server:
  port: 8080
spring:
  application:
    name: "Test_Technical"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/test_meli"
    username: "sa"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
