management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "always"
server:
  port: 8080
  servlet:
    context-path: "/api/testTechnical/v1"
spring:
  application:
    name: "Test_Technical"
  devtools:
    add-properties: false
  profiles:
    include: null
adapter:
  restconsumer:
    url: "http://localhost:8080"
